#-
#              _                        _   _
#   __ _ _   _| |_ ___  _ __ ___   __ _| |_(_) ___  _ __  ___
#  / _` | | | | __/ _ \| '_ ` _ \ / _` | __| |/ _ \| '_ \/ __|
# | (_| | |_| | || (_) | | | | | | (_| | |_| | (_) | | | \__ \
#  \__,_|\__,_|\__\___/|_| |_| |_|\__,_|\__|_|\___/|_| |_|___/
#
#
#- from github.com/basnijholt/home-assistant-config
