---
#-
#                   __ _                       _   _
#   ___ ___  _ __  / _(_) __ _ _   _ _ __ __ _| |_(_) ___  _ __
#  / __/ _ \| '_ \| |_| |/ _` | | | | '__/ _` | __| |/ _ \| '_ \
# | (_| (_) | | | |  _| | (_| | |_| | | | (_| | |_| | (_) | | | |
#  \___\___/|_| |_|_| |_|\__, |\__,_|_|  \__,_|\__|_|\___/|_| |_|
#                        |___/
#
#- from github.com/basnijholt/home-assistant-config

# Core Configuration
homeassistant: !include includes/homeassistant.yaml
default_config:
frontend:
  themes: !include_dir_merge_named themes
http: !include includes/http.yaml

# Inputs
input_boolean: !include includes/input_booleans.yaml
input_datetime: !include includes/input_datetimes.yaml
input_select: !include includes/input_selects.yaml
input_number: !include includes/input_numbers.yaml

# Logging and history
logger: !include includes/logger.yaml
recorder: !include includes/recorder.yaml

# Managed via UI
scene: !include scenes.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Others
person: !include includes/persons.yaml
zone: !include includes/zones.yaml
group: !include includes/groups.yaml
automation old: !include_dir_merge_list automations
switch: !include includes/switches.yaml
sensor: !include includes/sensors.yaml
command_line: !include includes/command_line.yaml
binary_sensor: !include includes/binary_sensors.yaml
shell_command: !include includes/shell_commands.yaml
notify: !include includes/notify.yaml
light: !include includes/lights.yaml
wake_on_lan:
proximity: !include includes/proximity.yaml
timer: !include includes/timers.yaml
ios: !include includes/ios.yaml
media_player: !include includes/media_players.yaml
homekit: !include includes/homekit.yaml
plant: !include includes/plant.yaml
influxdb: !include includes/influxdb.yaml
intent:
intent_script: !include includes/intent_script.yaml
panel_iframe: !include includes/panel_iframe.yaml

# Custom components
pyscript: !include includes/pyscript.yaml
adaptive_lighting: !include includes/adaptive_lighting.yaml
